id: P005421
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG24041
  title: ཁེར་རྐྱང་གི་བླ་སྲོག
  author: ''
  volumes:
    d561b21f7a9d43508d5b6cb1057f690f:
      image_group_id: I1KG24198
      title: ''
      volume_number: 1
      total_pages: 170
      base_file: v001.txt
