id: I341B8415
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T08:33:29+00:00'
last_modified: '2022-06-08T02:58:00.934456+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24041
  title: ཁེར་རྐྱང་གི་བླ་སྲོག
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    2EB7:
      image_group_id: I1KG24198
      title: ''
      total_pages: 170
      order: 1
      base_file: 2EB7.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
